services:
    gateway.api:
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - ASPNETCORE_HTTP_PORTS=8080
           - ASPNETCORE_HTTPS_PORTS=8081
           - ReverseProxy__Clusters__character-service__Destinations__destination1__Address=http://character.api:8080/
           - ReverseProxy__Clusters__identity-service__Destinations__destination1__Address=http://identity.api:8080/
        ports:
           - 5001:8080
           - 5051:8081
        volumes:
           - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
           - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
           - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
           - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
           - character.db
           - character.api
    character.db:
        container_name: character.db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=CharacterDB
        ports:
            - 6001:5432
        restart: always
        volumes:
            - character-postgres:/var/lib/postgresql/data/
    character.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ConnectionStrings__Database=Server=character.db;Port=5432;Database=CharacterDB;User Id=postgres;Password=postgres;Include Error Detail=true
        ports:
            - 5002:8080
            - 5052:8081
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            - character.db
    identity.db:
        container_name: identity.db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=IdentityDB
        ports:
            - 6000:5432
        restart: always
        volumes:
            - identity-postgres:/var/lib/postgresql/data/
    identity.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081    
            - ConnectionStrings__Database=Server=identity.db;Port=5432;Database=IdentityDB;User Id=postgres;Password=postgres;Include Error Detail=true
            - Jwt__Issuer=identity.api
            - Jwt__Audience=gm-toolset
            - Jwt__SecretKey=supersecretkeyyoushouldnotcommit
            - Jwt__ExpirationInMinutes= 10
            - Jwt__RefreshTokenExpirationInDays=7
        ports:
            - 5000:8080
            - 5050:8081
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro 
        depends_on:
            - identity.db