services:
    gateway.api:
        image: ${DOCKER_REGISTRY-}gatewayapi
        build:
          context: .
          dockerfile: Gateway/Gateway.API/Dockerfile
    character.db:
        image: postgres
    character.api:
        image: ${DOCKER_REGISTRY-}characterapi
        build:
            context: .
            dockerfile: Services/Character/Character.API/Dockerfile
volumes:    
    postgres: