services:
    gateway.api:
        image: ${DOCKER_REGISTRY-}gatewayapi
        build:
          context: .
          dockerfile: Gateway/Gateway.API/Dockerfile
    character.db:
        image: postgres
    character.api:
        image: ${DOCKER_REGISTRY-}characterapi
        build:
            context: .
            dockerfile: Services/Character/Character.API/Dockerfile
    identity.api:
        image: ${DOCKER_REGISTRY-}identityapi
        build:
            context: .
            dockerfile: Identity/Identity.API/Dockerfile
    identity.db:
        image: mcr.microsoft.com/mssql/server:2025-latest

volumes:    
    postgres:
    mssql: