global using Moq;
global using Marten;
global using Character.API.Features.CreateCharacter;
global using Character.API.Entities;
global using Common.Exceptions;
global using Marten.Exceptions;
global using Character.API.Exceptions;
global using Character.API.Features.DeleteCharacterById;
global using Character.API.Features.GetCharacterById;