name: Validate Tests
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  validate-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Run unit tests
        run: dotnet test ./Character.API.UnitTests/Character.API.UnitTests.csproj --verbosity normal
